services:
  sqlserver:
    env_file: .env.prod
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${DB_PASSWORD}
    restart: always

  bookstore.basket:
    env_file: .env.prod
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__basketdb: ${BASKET_CONN}
      ConnectionStrings__queue: ${QUEUE_CONN}
    restart: always

  bookstore.catalog:
    env_file: .env.prod
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__catalogdb: ${CATALOG_CONN}
      ConnectionStrings__queue: ${QUEUE_CONN}
      ConnectionStrings__redis: ${REDIS_CONN}
      Caching__MaximumPayloadBytes: ${CACHE_MAX_PAYLOAD_BYTES}
      Caching__Expiration: ${CACHE_EXPIRATION}
    restart: always

  bookstore.gateway:
    env_file: .env.prod
    restart: always