version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-bookstore}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-bookstore123!}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bookstore-network
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - bookstore-network

  bookstore.basket:
    build:
      context: .
      dockerfile: Services/Basket/BookStore.Basket/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
    networks:
      - bookstore-network

  bookstore.catalog:
    build:
      context: .
      dockerfile: Services/Catalog/BookStore.Catalog/Dockerfile
    depends_on:
      - sqlserver
    networks:
      - bookstore-network

  bookstore.gateway:
    build:
      context: .
      dockerfile: ApiGateWays/BookStore.Gateway/Dockerfile
    depends_on:
      - bookstore.basket
      - bookstore.catalog
    networks:
      - bookstore-network

volumes:
  sql_data:

networks:
  bookstore-network:
    driver: bridge