services:
  bookstore.basket:
    image: bookstore.basket:${IMAGE_TAG}
    env_file: .env.staging
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ConnectionStrings__basketdb: ${BASKET_CONN}
      ConnectionStrings__queue: ${QUEUE_CONN}
    restart: on-failure

  bookstore.catalog:
    image: bookstore.catalog:${IMAGE_TAG}
    env_file: .env.staging
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ConnectionStrings__catalogdb: ${CATALOG_CONN}
      ConnectionStrings__queue: ${QUEUE_CONN}
      ConnectionStrings__redis: ${REDIS_CONN}
      Caching__MaximumPayloadBytes: ${CACHE_MAX_PAYLOAD_BYTES}
      Caching__Expiration: ${CACHE_EXPIRATION}
    restart: on-failure

  bookstore.gateway:
    image: bookstore.gateway:${IMAGE_TAG}
    env_file: .env.staging
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - "5000:8080"
    restart: on-failure

  sqlserver:
    env_file: .env.staging
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${DB_PASSWORD}