services:
  bookstore.basket:
    image: bookstore.basket
    build:
      context: .
      dockerfile: Services/Basket/BookStore.Basket/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  
  bookstore.catalog:
    image: bookstore.catalog
    build:
      context: .
      dockerfile: Services/Catalog/BookStore.Catalog/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  bookstore.gateway:
    image: bookstore.gateway
    build:
      context: .
      dockerfile: ApiGateWays/BookStore.Gateway/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - bookstore.basket
      - bookstore.catalog

