services:
  bookstore.basket:
    image: bookstore.basket:${IMAGE_TAG}
    env_file: .env.staging
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ConnectionStrings__basketdb: ${BASKET_CONN}
    restart: on-failure

  bookstore.catalog:
    image: bookstore.catalog:${IMAGE_TAG}
    env_file: .env.staging
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ConnectionStrings__catalogdb: ${CATALOG_CONN}
    restart: on-failure

  bookstore.gateway:
    image: bookstore.gateway:${IMAGE_TAG}
    env_file: .env.staging
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - "5000:8080"
    restart: on-failure

  sqlserver:
    env_file: .env.staging
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${DB_PASSWORD}